#define BOARD_PID		"MAIPU-MPAX18"
#define BOARD_NAME		"MAIPU MPAX18"
#define BOARD_DESC		"MAIPU MPAX18 Wifi6 Router"
#define BOARD_VENDOR_NAME	"MAIPU"
#define BOARD_VENDOR_URL	"https://www.maipu.cn/"
#define BOARD_MODEL_URL		"https://www.maipu.cn/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120

#define BOARD_HAS_5G_11AC	1
#define BOARD_HAS_5G_11AX	1
#define BOARD_HAS_2G_11AX	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_NUM_ETH_EPHY	4
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
